import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { releaseScriptsOk, takeBuilderFiles, takePreloadBridge, PACK_EXCLUDE } from './pack-chrome.mjs'

const repo = join(dirname(fileURLToPath(import.meta.url)), '../../..')

describe('consumer pack + sandbox proofs — T-109 T-110', () => {
  it('createWindow sandboxes the renderer; prod scripts drop ELECTRON_DISABLE_SANDBOX', () => {
    const main = readFileSync(join(repo, 'apps/desktop/src/main/index.ts'), 'utf8')
    assert.match(main, /sandbox:\s*true/)
    assert.equal(/sandbox:\s*false/.test(main), false)
    assert.match(main, /webviewTag:\s*false/)
    assert.match(main, /contextIsolation:\s*true/)
    assert.match(main, /nodeIntegration:\s*false/)
    assert.match(main, /loadRoots/)
    const paths = readFileSync(join(repo, 'apps/desktop/src/main/paths.ts'), 'utf8')
    assert.match(paths, /takeAppRoots/)
    assert.match(main, /homeai:model:download/)
    assert.match(main, /takePartialDest/)
    assert.match(main, /takeGgufReady/)
    assert.match(main, /sha256File/)
    assert.match(main, /HOMEAI_SMOKE/)
    assert.match(main, /seedLibraryIfMissing/)
    assert.match(main, /livePorts/)
    assert.equal(main.includes('homeai:fs:stat'), false)
    const pkg = JSON.parse(readFileSync(join(repo, 'package.json'), 'utf8'))
    assert.equal(releaseScriptsOk(pkg.scripts), true)
    assert.match(String(pkg.scripts.dev || ''), /ELECTRON_DISABLE_SANDBOX/)
    assert.equal(String(pkg.scripts.ide || '').includes('ELECTRON_DISABLE_SANDBOX'), false)
    assert.equal(String(pkg.scripts.preview || '').includes('ELECTRON_DISABLE_SANDBOX'), false)
    assert.equal(String(pkg.scripts.telegram || '').includes('ELECTRON_DISABLE_SANDBOX'), false)
    assert.match(String(pkg.scripts.pack || ''), /electron-builder/)
    assert.match(String(pkg.scripts.release || ''), /electron-builder/)
    assert.match(String(pkg.scripts.smoke || ''), /electron-smoke/)
    assert.ok(pkg.dependencies && pkg.dependencies['electron-updater'])
    const preload = readFileSync(join(repo, 'apps/desktop/src/preload/index.ts'), 'utf8')
    const bridge = takePreloadBridge(preload)
    assert.equal(bridge.onlyHomeai, true)
    assert.equal(preload.includes('dangerouslySetInnerHTML'), false)
  })

  it('electron-builder excludes AI Resources, secrets, GGUF; legal files exist; CI is SHA-pinned', () => {
    const yml = readFileSync(join(repo, 'electron-builder.yml'), 'utf8')
    for (const bit of PACK_EXCLUDE) {
      assert.ok(yml.includes(bit), bit)
    }
    assert.match(yml, /AppImage/)
    assert.match(yml, /deb/)
    assert.match(yml, /nsis/)
    assert.match(yml, /dmg/)
    assert.match(yml, /\*\*\/\*\.node/)
    assert.match(yml, /ts-intel/)
    assert.match(yml, /electron-updater|generic|github/)
    assert.equal(yml.includes('AI Resources/**'), true)
    const files = takeBuilderFiles()
    assert.ok(files.some((f) => f.includes('AI Resources')))
    for (const f of ['LICENSE', 'SECURITY.md', 'PRIVACY.md', 'TERMS.md']) {
      assert.equal(existsSync(join(repo, f)), true, f)
    }
    const wf = readFileSync(join(repo, '.github/workflows/ci.yml'), 'utf8')
    assert.equal(wf.includes('pull_request_target'), false)
    assert.match(wf, /uses: actions\/checkout@[0-9a-f]{40}/)
    assert.match(wf, /uses: actions\/setup-node@[0-9a-f]{40}/)
    assert.equal(/uses: actions\/checkout@v\d/.test(wf), false)
    assert.match(wf, /npm test/)
    assert.match(wf, /assert-hunt-prevent/)
    const settings = readFileSync(join(repo, 'apps/renderer/src/panes/SettingsPane.tsx'), 'utf8')
    assert.match(settings, /modelDownload/)
    assert.match(settings, /Download GGUF/)
    assert.match(settings, /hardwareGate/)
    assert.match(settings, /no Landlock/)
    assert.match(settings, /\[glass, setGlass\]/)
    assert.match(settings, /secretsSet/)
    assert.equal(settings.includes('dangerouslySetInnerHTML'), false)
    const shell = readFileSync(join(repo, 'apps/renderer/src/layout/WorkbenchShell.tsx'), 'utf8')
    assert.equal(shell.includes("from './Onboard'"), false)
    assert.equal(shell.includes('<Onboard'), false)
    assert.match(shell, /no Landlock/)
    const vendor = readFileSync(join(repo, 'vendor/fetch-llama-server.sh'), 'utf8')
    assert.match(vendor, /HEX_LLAMA_ASSET/)
    const llm = readFileSync(join(repo, 'packages/llm/src/index.ts'), 'utf8')
    assert.match(llm, /llama-server\.exe/)
    assert.equal(existsSync(join(repo, 'scripts/electron-smoke.mjs')), true)
    const smoke = readFileSync(join(repo, 'scripts/electron-smoke.mjs'), 'utf8')
    assert.match(smoke, /takeChromeSandboxSkip/)
    assert.equal(smoke.includes('ELECTRON_DISABLE_SANDBOX=1'), false)
    const seed = readFileSync(join(repo, 'apps/desktop/src/main/seed.ts'), 'utf8')
    assert.match(seed, /takeLibraryStub/)
    assert.match(seed, /seedLibraryIfMissing/)
  })
})
